name: Run JRuby Script on HTML Change

on:
  push:
    paths:
      - '**/*.html'

jobs:
  run-jruby-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JRuby
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install JRuby
      run: |
        wget https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.2.13.0/jruby-complete-9.2.13.0.jar -O jruby-complete.jar
        echo 'alias jruby="java -jar $PWD/jruby-complete.jar"' >> $GITHUB_ENV
        echo 'export PATH=$PWD:$PATH' >> $GITHUB_ENV

    - name: Install Bundler
      run: jruby -S gem install bundler

    - name: Install Dependencies
      run: jruby -S bundle install

    - name: Run JRuby Script
      run: jruby helloworld.rb
