name: Run JRuby Script on HTML Change

on:
  push:
    paths:
      - 'form.html'

jobs:
  run-jruby-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22.0.2'

    - name: Install JRuby
      run: wget https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.4.8.0/jruby-complete-9.4.8.0.jar -O jruby-complete.jar

    - name: Install Bundler
      shell: bash
      run: |
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar -S gem install bundler

    - name: Install Dependencies
      shell: bash
      run: |
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar -S bundle install

    - name: Run JRuby Script
      shell: bash
      run: |
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar helloworld.rb
