name: Run JRuby Script on HTML Change

on:
  push:
    paths:
      - 'form.html'

jobs:
  run-jruby-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22.0.2'

    - name: Install JRuby
      run: wget https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.4.8.0/jruby-complete-9.4.8.0.jar -O jruby-complete.jar

    - name: Install Bundler
      shell: bash
      run: |
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar -S gem install bundler

    - name: Install Dependencies
      shell: bash
      run: |
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar -S bundle install

    # - name: Run JRuby Script
    #   shell: bash
    #   run: |
    #     GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar helloworld.rb
    - name: Capture Initial State
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar capture_initial_state.rb

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Set this to the root directory
        publish_branch: gh-pages  # Ensure this matches your GitHub Pages branch

    - name: Detect Changes
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar detect_changes.rb

    - name: Update Locators
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar update_locators.rb
