name: Run JRuby Script on HTML Change

on:
  push:
    paths:
      - '**/*.html'

jobs:
  run-jruby-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JRuby
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22.0.2'

    - name: Install JRuby
      run: |
         wget https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.4.8.0/jruby-complete-9.4.8.0.jar -O jruby-complete.jar
         echo 'export JRUBY_HOME=$PWD/jruby-complete.jar' >> $GITHUB_ENV
         echo 'alias jruby="java -jar $JRUBY_HOME"' >> $GITHUB_ENV
         echo 'export PATH=$PWD:$PATH' >> $GITHUB_ENV

    - name: Install Bundler
      shell: bash
      run: |
        source $GITHUB_ENV
        jruby -S gem install bundler

    - name: Install Dependencies
      shell: bash
      run: |
        source $GITHUB_ENV
        jruby -S bundle install

    - name: Run JRuby Script
      shell: bash
      run: |
        source $GITHUB_ENV
        jruby helloworld.rb
