name: CI/CD Pipeline for GitHub Pages Deployment

on:
  push:
    paths:
      - '**.html'  # Trigger on changes to HTML files

jobs:
  change-detection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22.0.2'

    - name: Install JRuby
      run: wget https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.4.8.0/jruby-complete-9.4.8.0.jar -O jruby-complete.jar

    - name: Install Bundler
      shell: bash
      run: |
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar -S gem install bundler

    - name: Install Dependencies
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar -S bundle install

    - name: Capture Initial State
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar $GITHUB_WORKSPACE/capture_initial_state.rb

  deploy:
    runs-on: ubuntu-latest
    needs: change-detection

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git fetch origin
        git worktree add gh-pages origin/gh-pages || git worktree add gh-pages --no-checkout
        rsync -av --progress --exclude='gh-pages' --exclude='.git' $GITHUB_WORKSPACE/ gh-pages/
        cd gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
        git push origin gh-pages

  update-locators:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22.0.2'

    - name: Install JRuby
      run: wget https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.4.8.0/jruby-complete-9.4.8.0.jar -O jruby-complete.jar

    - name: Install Bundler
      shell: bash
      run: |
        GEM_HOME=$HOME/.gem GEM_PATH=$HOME/.gem java -jar jruby-complete.jar -S gem install bundler

    - name: Install Dependencies
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        GEM_HOME=$HOME/.gem GEM PATH=$HOME/.gem java -jar jruby-complete.jar -S bundle install

    - name: Detect Changes
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        GEM_HOME=$HOME/.gem GEM PATH=$HOME/.gem java -jar jruby-complete.jar $GITHUB_WORKSPACE/detect_changes.rb

    - name: Update Locators
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        GEM_HOME=$HOME/.gem GEM PATH=$HOME/.gem java -jar jruby-complete.jar $GITHUB_WORKSPACE/update_locators.rb
